[package]
name = "ntcp-packetdrill"
version = "0.0.1"
edition = "2024"
publish = false
license = "GPL-2.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
ntcp-socket = { path = "../../crates/adapters/ntcp-socket", version = "0.0.1", features = ["packet-test"] }

[dev-dependencies]
ntcp = { path = "../../crates/ntcp", version = "0.0.1" }
ntcp-ip = { path = "../../crates/ntcp-ip", version = "0.0.1" }
