[package]
name = "ntcp"
version = "0.0.1"
edition = "2024"
description = "A standards-first, event-driven TCP stack in Rust"
license = "MIT"
repository = "https://github.com/minhuw/ntcp"
readme = "../../README.md"
keywords = ["tcp", "networking", "event-driven"]
categories = ["network-programming"]
include = ["/src/**", "/examples/**", "/tests/**", "/Cargo.toml", "/README.md", "/LICENSE"]

[dependencies]
hmac = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
libc = "0.2"
ntcp-ip = { version = "0.0.1", path = "../ntcp-ip" }
ntcp-io = { version = "0.0.1", path = "../ntcp-io" }
